apiVersion: v1
kind: Service
metadata:
  name: demo-web-service
spec:
  type: LoadBalancer # ClusterIP(default) - for internal use | NodePort | LoadBalancer
  selector:
    app: demo-web-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
